name: Build site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'
          extended: true
      - name: Set up dart-sass-embedded
        run: |
          wget -O sass_embedded.tar.gz https://github.com/sass/dart-sass-embedded/releases/download/1.0.0-beta.6/sass_embedded-1.0.0-beta.6-linux-x64.tar.gz
          tar -xvzf ./sass_embedded.tar.gz
          echo "./sass_embedded" >> $GITHUB_PATH
      - name: Build with Hugo
        run: hugo
