name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:  
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check-out source
        uses: actions/checkout@v2
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'
          extended: true
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Build site
        uses: ./.github/actions/build
      - name: Deploy to Netlify as production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy --prod
