name: Build and Publish Site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out source
        uses: actions/checkout@v2
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'
          extended: true
      - name: Set up dart-sass-embedded
        run: |
          wget -O sass_embedded.tar.gz https://github.com/sass/dart-sass-embedded/releases/download/1.0.0-beta.6/sass_embedded-1.0.0-beta.6-linux-x64.tar.gz
          tar -xvzf ./sass_embedded.tar.gz
          echo "./sass_embedded" >> $GITHUB_PATH
      - name: Build site
        run: hugo
      - name: Upload built site
        uses: actions/upload-artifact@v2
        with:
          name: publish-latest
          path: public/
          retention-days: 7
  
  publish-preview:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check-out source
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: publish-latest
          path: public
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy
